# Require all model files.
require 'wordpress/ar/database'
require 'wordpress/ar/user'
require 'wordpress/ar/usermeta'
require 'wordpress/ar/post'
require 'wordpress/ar/postmeta'
require 'wordpress/ar/comment'
require 'wordpress/ar/commentmeta'
require 'wordpress/ar/link'
require 'wordpress/ar/term'
require 'wordpress/ar/term_taxonomy'
require 'wordpress/ar/term_relationship'